// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hsmmhrjgtgwxgktgeszu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhzbW1ocmpndGd3eGdrdGdlc3p1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAwNDY0MjUsImV4cCI6MjA4NTYyMjQyNX0.2-jzKZHPfdfzZef8cVuW1MHmCK3BuhY1_nHCN0pfPQQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});